pub mod budget;
pub mod capture;
pub mod code_evidence;
pub mod config;
pub mod core;
mod embedding;
pub mod error;
pub mod hooks;
pub mod mcp;
pub mod measure;
pub mod notes;
pub mod operations;
pub mod policy;
mod presentation;
pub mod process;
pub mod publication;
mod reconcile;
pub mod records;
pub mod redact;
pub mod remote;
pub mod repository;
pub mod retrieval;
pub mod store;
pub mod tombstone;
pub mod util;
pub mod vectors;
mod verification;
